--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.60.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 14-04-2025 19:34:01
-- Server version: 10.4.32
--

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE task_manager;

--
-- Drop table `tasks`
--
DROP TABLE IF EXISTS tasks;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Set default database
--
USE task_manager;

--
-- Create table `users`
--
CREATE TABLE users (
  id int(11) NOT NULL AUTO_INCREMENT,
  username varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `username` on table `users`
--
ALTER TABLE users
ADD UNIQUE INDEX username (username);

--
-- Create table `tasks`
--
CREATE TABLE tasks (
  id int(11) NOT NULL AUTO_INCREMENT,
  title varchar(255) NOT NULL,
  description text DEFAULT NULL,
  status enum ('pending', 'in_progress', 'completed') DEFAULT 'pending',
  dueDate date DEFAULT NULL,
  user_id int(11) DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 12,
AVG_ROW_LENGTH = 1489,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE tasks
ADD CONSTRAINT tasks_ibfk_1 FOREIGN KEY (user_id)
REFERENCES users (id) ON DELETE CASCADE;

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(1, 'Nishant', '$2a$08$XikjFKE3hEvW07zifKjrruXLUsm8FDoVQW.uAqYHtHaqEvFksOVwW', '2025-04-14 16:58:11'),
(5, 'Abhishek', '$2a$08$biTKK/Vhol7zeG3kkkU/r.CZRAnP/Vjj7KxS8CVWkDwUGo9QrOId2', '2025-04-14 17:34:32');

-- 
-- Dumping data for table tasks
--
INSERT INTO tasks VALUES
(1, 'Buy groceries', 'Milk, Bread, Eggs, Fruits', 'pending', '2025-04-15', 1, '2025-04-14 17:58:01'),
(2, 'Development engineer', 'It services', 'in_progress', '2025-04-15', 1, '2025-04-14 18:00:37'),
(3, 'Buy Cars', 'Red,Black,White', 'in_progress', '2025-04-15', 1, '2025-04-14 18:27:05'),
(4, 'Buy Motors', 'Red,Black,White', 'in_progress', '2025-04-15', 1, '2025-04-14 18:27:16'),
(5, 'Buy Bicks', 'Red,Black,White', 'in_progress', '2025-04-15', 1, '2025-04-14 18:27:29'),
(6, 'Buy Bicks', 'Red,Black,White', 'in_progress', '2025-04-15', 1, '2025-04-14 18:27:30'),
(7, 'Buy Clothes', 'Red,Black,White', 'in_progress', '2025-04-15', 1, '2025-04-14 18:27:51'),
(8, 'Buy Clothes1', 'Red,Black,White', 'in_progress', '2025-04-15', 1, '2025-04-14 18:27:56'),
(9, 'Buy Software', 'Node.js,React.js', 'in_progress', '2025-04-15', 1, '2025-04-14 18:29:44'),
(10, 'Buy Software', 'Node.js,React.js', 'in_progress', '2025-04-15', 1, '2025-04-14 18:29:47'),
(11, 'Buy Orange', 'Orange is sweet', 'in_progress', '2025-04-15', 1, '2025-04-14 18:53:17');

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;